version: '3'

services:
  vue-app:
    container_name: vue_app_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:3000"
